- name: Change the working directory to somedir/ and run the command as db_owner if /path/to/database does not exist
  ansible.builtin.command:
    cmd: /usr/bin/make_database.sh db_user db_name
  become: yes
  become_user: db_owner
  chdir: somedir/
  args:
    chdir: somedir/
    creates: /path/to/database