skip_checks:
  - event: E903
  - event: W2603
  - event: H1900
    fqcn: sensu.sensu_go.user
  - event: W2600
    subevent_code: B411
    fqcn: inwx.collection.dns
enforce_checks:
  - event: W2600
    subevent_code: B324
    fqcn: community.aws.data_pipeline

