collections:
- name: microsoft.ad
  version: 1.2.0
- name: community.aws
  version: 6.0.0
- name: inwx.collection
  version: 1.3.0
- name: sensu.sensu_go
  version: 1.13.2
- name: amazon.aws
  version: 6.0.0
