---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Create security group.
      amazon.aws.ec2_security_group:
        name: "web-app-sec"
        description: "Sec group for app web-app"
        region: "us-west-1"
        access_key: "{{ ec2_access_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: result_sec_group

    - name: EC2 instance create.
      amazon.aws.ec2_instance:
        name: "VM_for_demo"
        vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        key_name: "prod-ssh-key"
        security_group: "default"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 254
              delete_on_termination: true
        image_id: ami-08c947c038321a605
        network:
          assign_public_ip: true
        tags:
          demo: VM

    - name: VPC info.
      steampunk.aws.ec2_vpc_info:
        auth:
          access_key: asdghfdgfhgtwfesdfghtgsfd
          secret_key: "{{ my_secret_key }}"
          region: "{{ my_region }}"
      register: vpcs

    - name: Create a new database with name "acme".
      community.postgresql.postgresql_db:
        db: acme

    - name: Insert data to the column of array type using positional_args.
      community.postgresql.postgresql_query:
        query: INSERT INTO test_table (array_column) VALUES (%s)
        positional_args:
        - '{1,2,3}'
      
    - name: Ensure that the desired snmp strings are present.
      cisco.ios.ios_config:
        lines:
          - snmp-server community ansible-public RO
          - reboot

    - name: Ensure user bob is present.
      ansible.windows.win_user:
        name: MSbob
#        fullname: Bob Something
        password: "{{ bob_password }}"
        password_expired: true
        password_never_expires: false
        state: present
        groups: 
          - Users
      no_log: false
     
    - name: Install plugin.
      community.general.jenkins_plugin:
        name: build-pipeline-plugin

