name: Test with Steampunk Spotter
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Scan Ansible content
        uses: xlab-steampunk/spotter-action@3.2.0
        with:
          sarif_file: example.sarif
        continue-on-error: true
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}

      - name: Read SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: example.sarif
